name: Release

on:
  push:
    branches:
      - "main"
      - "releases/**"
    tags:
      - v*
  pull_request:
    branches:
      - "releases/**"
    types: [opened, reopened, synchronize]

env:
  GO_VERSION: 1.18

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup go environment"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: "Cache Go modules"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: "Setup Environment"
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "GIT_REPO_URL=$(git remote get-url origin | sed -e 's|git@\(.*\):\(.*\)\.git|https://\1/\2|g')" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - name: Generate CHANGELOG.md
        run: |
          git-chglog --config=.github/CHANGELOG/config.yml --repository-url=${GIT_REPO_URL} -o CHANGELOG.md ${VERSION}
          git add CHANGELOG.md
          git commit -m "📄docs: update changelog for ${VERSION}"
          git push origin main
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
